# This workflow will build a Java project with Gradle initially
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Simple Pipe

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
      steps: 
    - id: report-count
      uses: clacroix-fnba/arg-count-action@main
      with: 
        arguments-to-count: ${{ github.event.inputs.myValues }}
    - run: echo 
    - shell: bash
      run: |
        echo argument count is ${{ steps.report-count.outputs.arg-count }}  

